services:
  spark-master:
    image: bitnami/spark:3.2.1
    container_name: spark-master
    networks:
      - sparknet
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark_applications:/usr/local/spark/applications            
      - ./spark_assets:/usr/local/spark/assets

  spark-worker-1:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-1
    networks:
      - sparknet
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    volumes:
      - ./spark_applications:/usr/local/spark/applications            
      - ./spark_assets:/usr/local/spark/assets 
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-2
    networks:
      - sparknet
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    volumes:
      - ./spark_applications:/usr/local/spark/applications            
      - ./spark_assets:/usr/local/spark/assets 
    depends_on:
      - spark-master

  spark-worker-3:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-3
    networks:
      - sparknet
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1  
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    volumes:
      - ./spark_applications:/usr/local/spark/applications            
      - ./spark_assets:/usr/local/spark/assets 
    depends_on:
      - spark-master

networks:
  sparknet:
    driver: bridge