services:
  clickhouse:
    image: clickhouse/clickhouse-server
    hostname: clickhouse
    volumes:
      - ./db:/var/lib/clickhouse
      - ./config/ch_config.xml:/etc/clickhouse-server/config.xml
      - ./log:/var/log/clickhouse-server
    container_name: clickhouse
    ports:
      - '8123:8123'
      - '9200:9000'
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=warehouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - insideout

networks:
  insideout:
    external: true