services:
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    networks:
      iceberg:
    ports:
      - 19120:19120

  minion1:
    image: bitnami/minio:2024
    container_name: minio-node-1
    networks:
      - iceberg
    environment:
      - MINIO_ROOT_USER=iykyk101
      - MINIO_ROOT_PASSWORD=44oki@iykyk
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minion1,minion2,minion3,minion4
    volumes:
      - 'minio_1_data:/bitnami/minio/data'
    ports:
      - 9100:9000
      - 9101:9001
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G

  minion2:
    image: bitnami/minio:2024
    container_name: minio-node-2
    networks:
      - iceberg
    environment:
      - MINIO_ROOT_USER=iykyk101
      - MINIO_ROOT_PASSWORD=44oki@iykyk
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minion1,minion2,minion3,minion4
    volumes:
      - 'minio_2_data:/bitnami/minio/data'
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G

  minion3:
    image: bitnami/minio:2024
    container_name: minio-node-3
    networks:
      - iceberg
    environment:
      - MINIO_ROOT_USER=iykyk101
      - MINIO_ROOT_PASSWORD=44oki@iykyk
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minion1,minion2,minion3,minion4
    volumes:
      - 'minio_3_data:/bitnami/minio/data'
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G

  minion4:
    image: bitnami/minio:2024
    container_name: minio-node-4
    networks:
      - iceberg
    environment:
      - MINIO_ROOT_USER=iykyk101
      - MINIO_ROOT_PASSWORD=44oki@iykyk
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minion1,minion2,minion3,minion4
    volumes:
      - 'minio_4_data:/bitnami/minio/data'
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G

volumes:
  minio_1_data:
  minio_2_data:
  minio_3_data:
  minio_4_data:

networks:
  iceberg:
    driver: bridge