services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_DOMAIN: storage
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
    ports:
      - 9100:9000
      - 9101:9001
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - 'minio_data:/data'
    networks:
      - insideout

  nessie:
    image: projectnessie/nessie:latest
    ports:
      - 19120:19120
    container_name: nessie
    environment:
      NESSIE_VERSION_STORE_TYPE: ROCKSDB
      NESSIE_VERSION_STORE_PERSIST_ROCKS_DATABASE_PATH: /usr/data
    volumes:
      - 'nessie_catalog_store:/usr/data'
    user: root
    networks:
      - insideout

volumes:
  minio_data:
  nessie_catalog_store:

networks:
  insideout:
    external: true