services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - 9100:9000
      - 9101:9001
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - 'minio_data:/data'
    networks:
      - iceberg

  nessie:
    image: projectnessie/nessie:latest
    ports:
      - 19120:19120
    container_name: nessie
    networks:
      - iceberg

volumes:
  minio_data:

networks:
  iceberg:
    driver: bridge